### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by rfuehrer** [mrikirill/SynologyDDNSCloudflareMultidomain#10]
Hi @mrikirill ,

I noticed that the project does not include a license statement, so legally it is not actually open source. Is this intentional or would you rather have provided a free license such as MIT?

For this, the following notes from Github (https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#what-happens-if-i-dont-choose-a-license):

> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.
> 
> Even if this is what you intend, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository.
> 
>
>if you want to share your work with others, we strongly encourage you to include an open source license.

Are you okay with me bringing in a PR with MIT?

**Comment by mrikirill** [comment]
Hi @rfuehrer 
Yeah you're right thanks for that. I've added NIT license -> https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/pull/11

**Comment by rfuehrer** [comment]
Integrated via mrikirill/add-license-1:50fa65d
