### ISSUE TITLE
Unknown error while update IP adress

### ISSUE THREAD

**Issue by havastamas** [mrikirill/SynologyDDNSCloudflareMultidomain#18]
I have set up the lastest version of SynologyDDNSCloudflareMultidomain on my Synology, but when i configure the DDNS, the DSM reports unknow error.

I have tired the debug command, and it gives the following error:

Catchable fatal error: Argument 2 passed to updateCFDDNS::setRecord() must be an instance of string, null given, called in /usr/syno/bin/ddns/cloudflare.php on line 85 and defined in /usr/syno/bin/ddns/cloudflare.php on line 226

**Comment by jkrasinger** [comment]
Have installed the latest Version on My Synology Router. After setting up on my router got same error Message as @havastamas

**Comment by sdhawade** [comment]
Its a type hinting compatibility issue with PHP, you can edit line 226 as follows to get it to work
original : function setRecord($arHostData, string $ip, $type)
edit to : function setRecord($arHostData, $ip, $type)

**Comment by jkrasinger** [comment]
Thanks @sdhawade , now it's working.

**Comment by Yassine2217** [comment]
hi how much of record support script on synology dsm7 when i enter more than 5 subodmaine i got failed report with missed caracteres in the last record that i entred 

for example www.domaine.com---test.domaine.com---test2.domaine.com---test. in DDNS server Cloudflare. The reported reason is [Incorrect hostname format.].

**Comment by Yassine2217** [comment]
> hi how much of record support script on synology dsm7 when i enter more than 5 subodmaine i got failed report with missed caracteres in the last record that i entred
> 
> for example [www.domaine.com---test.domaine.com---test2.domaine.com---test](http://www.domaine.com---test.domaine.com---test2.domaine.com---test). in DDNS server Cloudflare. The reported reason is [Incorrect hostname format.].

I did not see the issue above, thank you

https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/issues/17
