### ISSUE TITLE
DualStack: Only one record gets updated

### ISSUE THREAD

**Issue by Hoempi** [mrikirill/SynologyDDNSCloudflareMultidomain#22]
I got both a dynamic IPv4 and IPv6 address. But only the IPv4 gets updated. For Synology DDNS both entries get updated, so it seems to be possible.

**Comment by mrikirill** [comment]
This script supports both ipv4 and ipv6. Synology only provides ipv4 and the script get ipv6 from https://api64.ipify.org 
For using both ipv4 and ipv6 you have to have A and AAAA records created. You can see this logic [here](https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/blob/master/cloudflare.php#L84).
Probably in your case you don't have AAAA created record or https://api64.ipify.org couldn't detect your ipv6

**Comment by mrikirill** [comment]
Fixed here -> https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/pull/45
