### ISSUE TITLE
FYI CloudFlare API free domain limitation

### ISSUE THREAD

**Issue by pdjohntony** [mrikirill/SynologyDDNSCloudflareMultidomain#28]
Not exactly an issue but I wanted to pass this along for any poor soul who spent countless hours trying to get this to work only to find out there is a CloudFlare API limitation with free domains.

I was testing this out with a free .ml domain to no avail. I tried curling the API myself only to find this response.

``` json
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 1038,
      "message": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
    }
  ],
  "messages": []
}
```

**Comment by mrikirill** [comment]
Might be helpful -> https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/issues/3#issuecomment-857760109

**Comment by pdjohntony** [comment]
Ah I missed that issue. No worries I had a paid domain I was able to use instead. You can close this issue, I just wanted to pass this info along. It may be helpful to put a note in the readme about this limitation to folks time.

**Comment by mrikirill** [comment]
thank you @pdjohntony I've added that info into Readme -> https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain#cloudflare-api-free-domains-limitation

**Comment by pdjohntony** [comment]
Thanks for the great work @mrikirill
