### ISSUE TITLE
Service provider not updating with new Cloudflare value

### ISSUE THREAD

**Issue by gazzeg** [mrikirill/SynologyDDNSCloudflareMultidomain#29]
When finised editing the ddns_provider.conf file I confirm the entrie has saved.

I then check the Service provider dropdown and its not showing.
Rebooted the device, confirmed the new Cloudeflare is still in the conf file and its still not showing.

**Comment by mrikirill** [comment]
@gazzeg 

Make sure that you follow the instruction here https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain#how-to-install
And have added 
```
 [Cloudflare]
  modulepath=/usr/syno/bin/ddns/cloudflare.php
  queryurl=https://www.cloudflare.com/
 ```
into /etc.defaults/ddns_provider.conf

There is no confirmed issue with this case, tested on my nas, everything works well
