### ISSUE TITLE
Wildcard DNS record

### ISSUE THREAD

**Issue by bulvinkln** [mrikirill/SynologyDDNSCloudflareMultidomain#30]
How can I add wildcard (*.domain.com) DNS record?
DSM hostname string does not accept asterisk operator *.

![image](https://user-images.githubusercontent.com/24629969/204758753-7238c1be-0ddd-4c49-9914-d2e9e1586925.png)

**Comment by mrikirill** [comment]
@bulvinkln 

Unfortunately, the hostname input of Synology DSM doesn't support wildcard symbols. As an option to bypass this case you can pass your hostname string including wildcard (*.domain1.com---domain2.com---etc.com) directly into the script.

Or feel free to modify the script with a logic to replace a combination of allowed symbols into a wildcard symbol. For example, `///` replace with in the script `*` (see the line 66 as an example of that replacement)

**Comment by bulvinkln** [comment]
How I solved this issue:
line 49
$hostnames = (string) $argv[1];      // use name/email field $account instead of $hostList

line 70
if(!preg_match("/^(([\w-]+\.)|(\*\.))+[\w-]+$/", $value)) {      //regex for wildcard domains

Synology hostname field not used and can be filled with "null", or whatever. Domains string in DSM name/email field

**Comment by jeffxt** [comment]
@bulvinkln Does modified script still work?  I'm getting the error `Failed to connect to the server.  Please check the network connection of the server.`
