### ISSUE TITLE
Unable to update wildcard domain

### ISSUE THREAD

**Issue by HA-Roberto** [mrikirill/SynologyDDNSCloudflareMultidomain#33]
I use '*' in my cloudflare DNS to allow access to any ABC.mydomain.com instead of having to define each ABC name in the DNS. 
Synology doesnt seem to accept the character '*' in the hostname field when configuring the connection. Is there a way around this?

Thanks!

**Comment by domenix** [comment]
You can consider using a CNAME record that you just point to your A record domain that you defined already and is set up in the DDNS. This way, you don't need to update the IP address of the wildcard record separately.

**Comment by jeffxt** [comment]
Has anyone found a fix or workaround?  I'm running into the same issue

**Comment by spdavern** [comment]
> You can consider using a CNAME record that you just point to your A record domain that you defined already and is set up in the DDNS. This way, you don't need to update the IP address of the wildcard record separately.

When I tried this on Cloudflare it seems to cause a cyclical reference causing the domain to be unresolvable. So, `*.mysite.com CNAME mysite.com` while possibly being allowed by some providers doesn't seem to work for Cloudflare.

The only workaround I can find it to manually update the wildcard record.  At least the new IP address is available on the records that get updated. :-(

**Comment by spdavern** [comment]
Would it work for cloudflare.php to search and replace `---asterisk---` with `*` before further processing the string?  Thus, `---asterisk---.mysite.com` would become `*.mysite.com`.

**Comment by borbmizzet** [comment]
If I'm not mistaken, it looks like the regex in isValidHostname() might not account for wildcards.  Could that be the issue?
