### ISSUE TITLE
Suggestion for an automatic installer in Python

### ISSUE THREAD

**Issue by aleclerc7** [mrikirill/SynologyDDNSCloudflareMultidomain#35]
Hello,

I came across someone who made a nice automatic installer, very easy to use, made in Python. A very simple cron job is set up and it runs the script at every boot-up. It thus makes sure it is always working, even after a DSM update (theoretically).

The original script is there: https://github.com/namukcom/SynologyCloudFlareDDNS/blob/master/setddns.py
I made a variant of it there: https://github.com/aleclerc7/SynologyCloudflareDDNS/blob/master/CloudflareSynologyDDNSProvider.py

Maybe adding such a script could make the life easier for many. One can just make a fork and make the necessary path change if he wants to be in control of what is downloaded to his Synology DSM. Then, it just works, even after an upgrade of DSM.

Kind regards.

**Comment by mrikirill** [comment]
Hi @aleclerc7 
I like the idea :+1:  also was thinking about making a package and add it to **SynoCommunity Repo**
https://github.com/SynoCommunity/spksrc

**Comment by mrikirill** [comment]
Added auto installer script in the new version -> https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/pull/41
