### ISSUE TITLE
Synology DMS DDNS list isn't updated

### ISSUE THREAD

**Issue by 6Leoo6** [mrikirill/SynologyDDNSCloudflareMultidomain#39]
I updated the DDNS config file following the instructions, downloaded the "cloudfare.php" file to the correct place and even ran the debug command through SSH, but Cloudfare still wouldn't show up in my list. I tried changing the name of Google just to test it, but it didn't update either.

**Comment by Forge36** [comment]
I'm about to try this. Did you restart after making the changes?

**Comment by 6Leoo6** [comment]
Thank you for your reply! I've restarted it once after setting up the script and did it again now, just to be sure, but still nothing.

**Comment by Forge36** [comment]
Hmm... mine reports to work without restarting (return success and says it's registered. I don't know that I have had an IP change to confirm yet).

>wget https://raw.githubusercontent.com/mrikirill/SynologyDDNSCloudflareMultidomain/master/cloudflare.php -O /usr/syno/bin/ddns/cloudflare.php && sudo chmod 755 /usr/syno/bin/ddns/cloudflare.php

Couple of guesses:
1. This file has the wrong permissions
Do all files match permission? `ls -l /usr/syno/bin/ddns` 
2. Is the file ownership by the same user?

And you edited `/etc.defaults/ddns_provider.conf`?
Does it end in a new line?

**Comment by 6Leoo6** [comment]
Thank you for all your help and suggestions. My issue was fixed after the config file mysteriously reset and I pasted in the Cloudflare lines again. Maybe it was the number of spaces before the text that caused the issue, as last time after I pasted in the lines, I put a few additional ones in front of them to line them up with the other configs.
