### ISSUE TITLE
Avoid 128 chars limitation

### ISSUE THREAD

**Issue by alevangel** [mrikirill/SynologyDDNSCloudflareMultidomain#40]
I'm facing with chars limitations of 128 symbols... any way to avoid it? I can only add one DDNS for a single provider.

I have lots of domains to update 😭 

At the moment I edited directly the cloudflare.php file to hard encode the long string.  Just as fast fix.

**Comment by longkenj** [comment]
> I'm facing with chars limitations of 128 symbols... any way to avoid it? I can only add one DDNS for a single provider.
> 
> I have lots of domains to update 😭
> 
> At the moment I edited directly the cloudflare.php file to hard encode the long string. Just as fast fix.

hi alevangel,
can you please provide me with the cloudflare.php file that you have edited to fix the 128 character limit? I also have many subdomains and am limited.

**Comment by alevangel** [comment]
@longkenj I just edited this line, and added the string I need. In this way they don't use the input you provide in the UI. 

https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/blob/9edf73646dd8b38b117539817b13609cf276948b/cloudflare.php#L49C9-L49C107

**Comment by mrikirill** [comment]
updated in the new version -> https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/pull/41
