### ISSUE TITLE
Question about IPv4 and IPv6 Address Handling in Script

### ISSUE THREAD

**Issue by KiloNiner** [mrikirill/SynologyDDNSCloudflareMultidomain#44]
Hi,

I like what you've built here, but I've noticed the script always ignores the IPv4 address when there's an IPv6 address present. I created both A and AAAA records in Cloudflare, but only the AAAA records get updated. Looking at the script, it seems IPv4 is consistently ignored if IPv6 is available. Could you explain why this is, and if it's possible for the script to register both addresses?

Thanks!

**Comment by KiloNiner** [comment]
My question seems somewhat related to #22, but the question is old and he has the inverse problem, so I'm pretty sure the cause is not the same.

**Comment by mrikirill** [comment]
Hi @KiloNiner,

Thank you for reporting about the case with both records A and AAAA. Yes, you're right the script didn't covered both case. 
Made the update which covers this case -> https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/pull/45
