### ISSUE TITLE
Unable to update IPv6

### ISSUE THREAD

**Issue by kevin860708** [mrikirill/SynologyDDNSCloudflareMultidomain#47]
When I use debug command to check ipv4, the result is **good**
but when I use debug command to check ipv6, it shows **badagent**

Can anyone help to resolve this issue?
This issue happened both SRM and DSM.
Thanks

**Comment by mrikirill** [comment]
You can’t pass IPv6 address with the debug command because Synology only passes IPv4 address as an input parameter. IPv6 is automatically detected via ipify.org.

See the relevant code here:
https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/blob/master/cloudflare.php#L243


```
/usr/bin/php -d open_basedir=/usr/syno/bin/ddns -f /usr/syno/bin/ddns/cloudflare.php "domain1.com|vpn.domain2.com" "your-CloudFlare-token" "" "only IPv4 address the same as Synology passes"
```
