### ISSUE TITLE
Unable to update IP

### ISSUE THREAD

**Issue by veniplex** [mrikirill/SynologyDDNSCloudflareMultidomain#51]
Hi, Iam using Synology NAS DSM 7.2.1. The script runned fine until a few days ago. I always got the error `Unable to register the IP address xx.xxx.xxx.xxx to xxxx.xxxx.xxx via DDNS service.` under more details I can see `Authentication failed.`. Also when I run the script mentioned in the readme.md to debug, I get the response `badauth`. So I assume this is an authorization error. However, I re-installed the script first as explained in the readme.md. I created a completley new API token with all the necessary permissions etc. Whatever I do, I always run into this authorization problem...

Log from installation:
```
sudo wget https://raw.githubusercontent.com/mrikirill/SynologyDDNSCloudflareMultidomain/master/install.sh -O install.sh && sudo bash install.sh
--2024-10-04 13:30:08--  https://raw.githubusercontent.com/mrikirill/SynologyDDNSCloudflareMultidomain/master/install.sh
Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1490 (1.5K) [text/plain]
Saving to: 'install.sh'

install.sh                    100%[===============================================>]   1.46K  --.-KB/s    in 0s      

2024-10-04 13:30:08 (26.4 MB/s) - 'install.sh' saved [1490/1490]


[INFO] Downloading cloudflare.php...

--2024-10-04 13:30:09--  https://raw.githubusercontent.com/mrikirill/SynologyDDNSCloudflareMultidomain/master/cloudflare.php
Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14826 (14K) [text/plain]
Saving to: '/tmp/cloudflare.php'

/tmp/cloudflare.php           100%[===============================================>]  14.48K  --.-KB/s    in 0.001s  

2024-10-04 13:30:09 (16.6 MB/s) - '/tmp/cloudflare.php' saved [14826/14826]


[INFO] Copying cloudflare.php to /usr/syno/bin/ddns/cloudflare.php...


[INFO] Changing permissions of cloudflare.php...


[INFO] Adding Cloudflare configuration to ddns_provider.conf...


[INFO] Cloudflare configuration already exists in ddns_provider.conf. Skipping...


[INFO] Deleting the installation script...


[INFO] Installation completed.
```

Log from debug script:
```
/usr/bin/php -d open_basedir=/usr/syno/bin/ddns -f /usr/syno/bin/ddns/cloudflare.php "subdomain.domain.tld" "API_TOKEN" "" "EXTERNAL_IP"
badauth
```

Config inside DSM:
<img width="674" alt="Bildschirmfoto 2024-10-04 um 13 46 49" src="https://github.com/user-attachments/assets/f7f135e6-2406-4146-80fb-7d6c750bd43d">

API Token config:
<img width="991" alt="Bildschirmfoto 2024-10-04 um 13 48 39" src="https://github.com/user-attachments/assets/e705f2d3-ee91-4d56-9eb8-40853f34c27f">

I have absolutely no idea...

**Comment by mrikirill** [comment]
Hi @veniplex 

A [2.0 update](https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/releases/tag/2.0) was released a few months ago and the setup process has been updated (DSM part). Based on the screenshots you provided  looks like your DSM settings were configured a bit incorrectly. Please check the [installation steps](https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain?tab=readme-ov-file#how-to-install) to ensure your settings are correct.
![example3](https://github.com/user-attachments/assets/584137c3-0b10-45b0-828b-e628f9362eb5)

**Comment by veniplex** [comment]
Ohhhhhh now I see it 😂... Thank you, I will test it tomorrow!

**Comment by veniplex** [comment]
It should be correct now, but it is still not working:
![image](https://github.com/user-attachments/assets/743cb120-0c73-4a7f-9211-80c54afda2ed)

**Comment by mrikirill** [comment]
You could try to [debug the script](https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain?tab=readme-ov-file#debug) on your end and check the return status:

>good - Update successfully.
>
>nochg - Update successfully but the IP address have not changed.
>
>nohost - The hostname specified does not exist in this user account.
>
>abuse - The hostname specified is blocked for update abuse.
>
>notfqdn - The hostname specified is not a fully-qualified domain name.
>
>badauth - Authenticate failed.
>
>911 - There is a problem or scheduled maintenance on provider side
>
>badagent - The user agent sent bad request(like HTTP method/parameters is not permitted)
>
>badresolv - Failed to connect to because failed to resolve provider address.
>
>badconn - Failed to connect to provider because connection timeout.

**Comment by veniplex** [comment]
I took a look at my Cloudflare logs and I cannot find any API requests. So it might also be a port issue... I didn't change anything so this is strange. Is there any specific port that needs to be open besides 80/443? I can see a list of Cloudflare ports in the readme, but are they all necessary to be open?

**Comment by veniplex** [comment]
I have found the issue. I somehow landed on the wrong API page at Cloudflare. I don't understand the difference, but https://dash.cloudflare.com/profile/api-tokens is the right place and **not** the one under `Manage Account -> Account API Tokens (Beta)`. Confusing..
